spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: NISHANT
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: BANKAR
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    show-sql: true
